### ISSUE TITLE
nvim compilers

### ISSUE THREAD

**Issue by con-f-use** [phelipetls/dotfiles#2]
Read your [vim errorformat for pytest](https://phelipetls.github.io/posts/vim-errorformat-for-pytest/) article.

I'm not sure how in your current dotfiles https://github.com/phelipetls/dotfiles/blob/master/.config/nvim/init.vim the `current_compiler` ever gets set, or how `compilers/pytest.lua` would get loaded. It seems to me, you'd have to set the compiler manually and then `:source ~/.config/nvim/compilers/pytest.lua` by hand. Can you shed a bit of light on that for me?

**Comment by phelipetls** [comment]
I call `:compiler pytest` if the filename without extension starts or ends with "test". See here: https://github.com/phelipetls/dotfiles/blob/master/.config/nvim/after/ftplugin/python.vim#L5:L12
