### ISSUE TITLE
bat install task is incorrect for macos

### ISSUE THREAD

**Issue by kyteinsky** [phelipetls/dotfiles#6]
Hi, I was reading your blog on Ansible, which is very nice and thank you for that, when I stumbled upon this repo.  
Looking around I found the macos install of `bat` is not done correctly: https://github.com/phelipetls/dotfiles/blob/master/roles/cli/tasks/bat.yml#L15-L21

**Comment by phelipetls** [comment]
Thanks for letting me know. I'll double check later and fix the blog post as well.

**Comment by phelipetls** [comment]
Oh sorry, I see, using `dnf` in macOS🤦. I don't have a macOS anymore so this tends to happen

**Comment by kyteinsky** [comment]
No issues, I don't either, just noticed it was off :v:
